version: '3.8'
services:
  web:
    build: .
    ports:
      - 8081:80
    container_name: web
    volumes:
      - user-web:/usr/share/nginx/html
  firefox:
    image: jlesage/firefox
    ports:
        - 5800:5800
    volumes: 
        - my-vol:/data/db
    depends_on: 
            - web
    
    container_name: firefox        
    shm_size: "2gb"
        
volumes:
     my-vol:
        driver: local
     user-web:
        driver: local
